### ISSUE TITLE
wrong judgment condition of train epochs

### ISSUE THREAD

**Issue by j-cyoung** [shaoshitong/G_VBSM_Dataset_Condensation#4]
As writen in the [Branch_CIFAR_10/squeeze/squeeze.sh](https://github.com/shaoshitong/G_VBSM_Dataset_Condensation/blob/main/Branch_CIFAR_10/squeeze/squeeze.sh) and the paper supplemental, the total epochs of pretrained model is `5`

```bash
python train.py --model ResNet18 --dataset CIFAR-10 --data_path /path/to/cifar-10 --train_epochs 5

python train.py --model MobileNetV2 --dataset CIFAR-10 --data_path /path/to/cifar-10 --train_epochs 5

python train.py --model ShuffleNetV2_0_5 --dataset CIFAR-10 --data_path /path/to/cifar-10 --train_epochs 5

python train.py --model WRN_16_2 --dataset CIFAR-10 --data_path /path/to/cifar-10 --train_epochs 5

python train.py --model ConvNetW128 --dataset CIFAR-10 --data_path /path/to/cifar-10 --train_epochs 5
```
![image](https://github.com/user-attachments/assets/a38f0761-fdeb-42a5-a16d-4459f76c5e54)

However it seems that the judgment condition in [Branch_CIFAR_10/squeeze/train.py](https://github.com/shaoshitong/G_VBSM_Dataset_Condensation/blob/main/Branch_CIFAR_10/squeeze/train.py) (line 121) cannot save the corresponding epoch:

```python
        if e % 10 == 0:
            state_dict = model.state_dict()
            torch.save(state_dict,os.path.join(save_dir,f"squeeze_{args.model}.pth"))
```

**Comment by shaoshitong** [comment]
Thanks for pointing out this issue, I will fix the code. From what we have observed the performance difference on steps 5-10 is not very big, if you want to store the result of step 5, you can modify `%10` to `%5`.

**Comment by j-cyoung** [comment]
Thanks for your reply and great work, I will close this issue.
