### ISSUE TITLE
CIFAR10 results much higher than reported in the paper

### ISSUE THREAD

**Issue by j-cyoung** [shaoshitong/G_VBSM_Dataset_Condensation#5]
While attempting to reproduce the GVBSM on the CIFAR-10 dataset, I found that the performance metrics I obtained are significantly higher than those reported in the paper. Even after I tried the checkpoints and distilled images provided by the authors, the reproduced results remained high.

|ipc|acc in paper|acc by provided ckpts/imgs|acc reproduced|
|-|-|-|-|
|10|53.5|52.96|62.96|
|50|59.2|80.47|77.51|

Below is a run summary with ipc=50 and the provided checkpoints and distilled images:
![image](https://github.com/user-attachments/assets/5222ef94-1171-4608-8b6a-5aeb58489fbb)

I didn't modify the hyperparameters except for the paths or devices, and I checked the hyperparameters to ensure consistency with the paper.

I am unsure why this is happening. Has anyone else encountered the same issue?

**Comment by shaoshitong** [comment]
Thank you for following our work! I'm not entirely sure, but it seems like you're modifying the hyperparameters, such as the test batch size or something similar.

**Comment by j-cyoung** [comment]
Thank you very much for your reply. I’ll give it another try.
